-- Migration 003: Future-proofing for Customers, Quotations, Invoices
-- ─────────────────────────────────────────────────────────────────────────────
-- All changes are backwards-compatible (ADD COLUMN with nullable/default,
-- or non-destructive type widening). Existing rows and queries are unaffected.


-- ── 1. Decimal quantities ─────────────────────────────────────────────────────
-- `integer` prevents fractional units (meters, kg, liters).
-- Changing this after invoice/quotation data accumulates requires a table
-- rewrite and a trigger redeploy — do it while the tables are still small.
alter table stock_levels
  alter column quantity type numeric(12,3) using quantity::numeric(12,3);

alter table stock_movements
  alter column quantity type numeric(12,3) using quantity::numeric(12,3);


-- ── 2. GST rate on products ───────────────────────────────────────────────────
-- Every invoice line needs a GST slab. Nullable so existing products don't
-- get a wrong default; the Invoices module validates that it is set before
-- creating a taxed line item.
alter table products
  add column if not exists tax_rate numeric(5,2)
    check (tax_rate >= 0 and tax_rate <= 100);


-- ── 3. Transaction-time price and discount on stock_movements ─────────────────
-- unit_price: the per-unit price charged or paid at the moment of the
--   movement. Joining back to price_history is unreliable (multiple changes
--   may have happened between the movement date and the query date).
-- discount_amount: line-level discount before tax. Needed for invoice lines
--   where a negotiated price differs from the catalogue selling_price.
-- Both nullable — existing ad-hoc movements have neither value.
alter table stock_movements
  add column if not exists unit_price      numeric(12,2),
  add column if not exists discount_amount numeric(12,2);


-- ── 4. Document linkage on stock_movements ────────────────────────────────────
-- Each movement generated by a business document (invoice, purchase order,
-- quotation) must trace back to it. A polymorphic pair (id + type) avoids
-- adding a new FK column for each future document type, while still
-- allowing a document-level JOIN:
--   WHERE document_id = $1 AND document_type = 'invoice'
alter table stock_movements
  add column if not exists document_id   uuid,
  add column if not exists document_type text
    check (document_type in ('invoice', 'purchase_order', 'quotation'));


-- ── 5. Customers table ────────────────────────────────────────────────────────
-- Mirrors vendors: same shape, same RLS pattern, same set_org_id trigger.
-- Kept minimal deliberately — the Customers module will add columns.
create table if not exists customers (
  id              uuid        primary key default uuid_generate_v4(),
  organization_id uuid        references organizations(id) on delete cascade,
  name            text        not null,
  contact_name    text,
  phone           text,
  email           text,
  address         text,
  gstin           text,
  is_active       boolean     not null default true,
  created_at      timestamptz not null default now()
);

alter table customers enable row level security;

create policy "org access: customers" on customers
  for all using (organization_id = auth_org_id());

create trigger customers_set_org_id
  before insert on customers
  for each row execute function set_org_id();


-- ── 6. customer_id on stock_movements ────────────────────────────────────────
-- Symmetric to vendor_id: receipts reference vendors, sales reference customers.
-- Nullable — ad-hoc movements and non-sale types have no customer.
alter table stock_movements
  add column if not exists customer_id uuid references customers(id);


-- ── 7. Indexes for the new FK and lookup columns ─────────────────────────────
create index if not exists idx_stock_movements_customer_id
  on stock_movements (customer_id) where customer_id is not null;

create index if not exists idx_stock_movements_document
  on stock_movements (document_id, document_type) where document_id is not null;

create index if not exists idx_customers_org
  on customers (organization_id);
